"""added image column to posts table

Revision ID: 6b9b7a4bc56b
Revises: c53ed64e0dff
Create Date: 2023-07-16 16:56:28.330944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9b7a4bc56b'
down_revision = 'c53ed64e0dff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image')
    # ### end Alembic commands ###
