"""added parent_id to posts table --> threading

Revision ID: b1ee6832f1e2
Revises: 6b9b7a4bc56b
Create Date: 2023-07-21 20:53:16.557532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ee6832f1e2'
down_revision = '6b9b7a4bc56b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('parent_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'parent_id')
    # ### end Alembic commands ###
